### ISSUE TITLE
ejabberd_auth_http bad argument in call to lists:keyfind

### ISSUE THREAD

**Issue by lefam** [processone/ejabberd-contrib#104]
I have installed the ejabberd_http contrib module and configured (ejabberd.yml) it like so:
```
auth_method: http
auth_opts:  
   host: "http://localhost:1212"
```
But, I get the error bellow:
[info] <0.7.0> Application ejabberd exited with reason: bad argument in call to lists:keyfind(host, 1, undefined) in ejabberd_auth_http:start/1 line 41

**Comment by badlop** [comment]
Hi, I've fixed this small problem. Maybe another problems appear in that module, because I didn't test it completely, and it seems nobody else did before in a lot of months (since ejabberd 2). So, please fill new issues if you find more problems.

I found a problem in ejabberd, that apparently you will not see. In any case, take it into account:
https://github.com/processone/ejabberd/issues/578

**Comment by lefam** [comment]
Ok. Thanks.

**Comment by dapriett** [comment]
So is this module not working then until the next version of EJabberd gets released?

**Comment by badlop** [comment]
Initially yes. But you can copy ejabberd_auth_htttp.beam with the other ejabberd beam files, and you don't need to wait for ejabberd's fix.
