### ISSUE TITLE
mod_multicast README looks autoconverted

### ISSUE THREAD

**Issue by RobertLarsen** [processone/ejabberd-contrib#108]
Does this seem right?
```
limits, "> [ {local,message,40}, {local,presence,infinite}, {remote,message,150} ]."
```

**Comment by badlop** [comment]
mod_multicast source code has been moved to ejabberd git repository. The documentation for mod_multicast is now available in a website. The syntax is correct, but it still had a typo (instead of , it must be :. It's fixed now, see:
http://docs.ejabberd.im/admin/guide/configuration/#modmulticast

Your question still remains: why does the example use that strange syntax? Because the Limits option can't be expressed using YAML syntax, so the example uses Erlang syntax. See an explanation here:
http://docs.ejabberd.im/admin/guide/configuration/#legacy-configuration-file

Anyway, thanks for commenting your doubts.
