### ISSUE TITLE
use service_url instead of put_url in mod_http_upload

### ISSUE THREAD

**Issue by Ivan-Masli-GDP** [processone/ejabberd-contrib#140]
I have defined the service_url in the mod_http_upload, but instead returning url specified in service_url, ejabberd returned the default put_url.
How do I config the mod_http_upload to use the service_url ?
This is my mod_http_upload config

mod_http_upload:
  #docroot: "@HOME@/upload"
  put_url: `'http://user:passwd@service.url'`
  service_url: 'http://user:passwd@service.url'
mod_http_upload_quota:
    max_days: 100

**Comment by victoralexanderds** [comment]
The cause could be the mod_http_upload read its own conf file instead of your ejabberd.yml.

The mod_http_upload conf file can be found under ejabberd_folder_home/.ejabberd-modules/mode_http_upload/conf

You can delete this file and mod_http_upload will read your ejabberd.yml.

Source: https://github.com/processone/ejabberd-contrib/issues/122
