### ISSUE TITLE
mod_s2s_log broken, prevents ejabberd 17.08 from starting

### ISSUE THREAD

**Issue by debalance** [processone/ejabberd-contrib#229]
I am running ejabberd 17.08 on Debian Stretch.

ejabberd.log:
> 2017-10-10 17:17:51.248 [warning] <0.258.0>@gen_mod:get_validators:495 module 'mod_s2s_log' doesn't export mod_opt_type/1

error.log :
> 2017-10-10 17:14:21.348 [critical] <0.236.0>@gen_mod:start_module:212 Problem starting the module mod_s2s_log for host [...]
 options: [{filename,<<"/var/log/ejabberd/s2s.log">>}]
 error: undef
[{mod_s2s_log,start,
              [<<"[hostname]">>,
               [{filename,<<"/var/log/ejabberd/s2s.log">>}]],
              []},
 {gen_mod,start_module,4,[{file,"src/gen_mod.erl"},{line,200}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {gen_mod,start_link,0,[{file,"src/gen_mod.erl"},{line,79}]},
 {supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},
 {supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},
 {supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},
 {gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]}]
2017-10-10 17:14:21.349 [critical] <0.236.0>@gen_mod:maybe_halt_ejabberd:294 ejabberd initialization was aborted because a module start failed.

**Comment by zinid** [comment]
The error means ejabberd doesn't see mod_s2s_log.beam file

On Oct 10, 2017 18:21, "Philipp Huebner" <notifications@github.com> wrote:

I am running ejabberd 17.08 on Debian Stretch.

ejabberd.log:

2017-10-10 17:17:51.248 [warning] <0.258.0>@gen_mod:get_validators:495
module 'mod_s2s_log' doesn't export mod_opt_type/1

error.log :

2017-10-10 17:14:21.348 [critical] <0.236.0>@gen_mod:start_module:212
Problem starting the module mod_s2s_log for host [...]
options: [{filename,<<"/var/log/ejabberd/s2s.log">>}]
error: undef
[{mod_s2s_log,start,
[<<"[hostname]">>,
[{filename,<<"/var/log/ejabberd/s2s.log">>}]],
[]},
{gen_mod,start_module,4,[{file,"src/gen_mod.erl"},{line,200}]},
{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
{gen_mod,start_link,0,[{file,"src/gen_mod.erl"},{line,79}]},
{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},
{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},
{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},
{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]}]
2017-10-10 17:14:21.349 [critical] <0.236.0>@gen_mod:maybe_halt_ejabberd:294
ejabberd initialization was aborted because a module start failed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/processone/ejabberd-contrib/issues/229>, or mute the
thread

**Comment by debalance** [comment]
It's in /usr/lib/x86_64-linux-gnu/ejabberd-17.08/ebin/ along with the rest.
mod_statsdx.beam e.g. is working.

**Comment by zinid** [comment]
I have another issue by the way:
```
18:47:14.138 [critical] Problem starting the module mod_s2s_log for host 192.168.1.1 
 options: []
 error: true
[{gen_mod,start_module,4,[{file,"src/gen_mod.erl"},{line,203}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {gen_mod,start_link,0,[{file,"src/gen_mod.erl"},{line,79}]},
 {supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},
 {supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},
 {supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},
 {gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},
 {gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]}]
```

**Comment by zinid** [comment]
Looking at the module, it won't work in recent versions for sure.

**Comment by zinid** [comment]
I'm checking if I can fix it quickly.

**Comment by zinid** [comment]
I fixed all the issues, but I have nowhere to test it.
Volunteers?
https://gist.github.com/zinid/9e91169be749fee9d6a86b99b2c84382

**Comment by debalance** [comment]
That gist is working perfectly!

**Comment by zinid** [comment]
Thanks for testing, I will commit it then :)

**Comment by zinid** [comment]
Fixed in https://github.com/processone/ejabberd-contrib/commit/6a4b9a08d53aea569a90b56ea0cd7212f301d413
